### PR TITLE
Remove bit_wrapper and discovery_api as this was causing issue on IE

### PR DESCRIPTION
**Pull request by zamanafzal**
There is an issue with the latest update of 2.0.18 on some IE specific version where the video is not working. So, the workaround for that is to remove the specific files causing issues on the IE.
I have removed the bit_wrapper and discovery_api file for now as it was causing an issue on some IE versions. So, by this change Captions will not work on any IE but the video will. The work on it will be done in MCKIN-8790.

@xitij2000  Can you please spare some time and have a look on it.

### CODE REVIEW

**Comment by lgp171188** [comment]
@zamanafzal, can you update the description of this PR to clarify what is the issue being fixed and also add testing instructions?

**Comment by lgp171188** [comment]
I tested this XBlock on the solutions devstack and found that with the changes in this PR branch, the video played fine but the captions weren't loading on IE 11. They loaded fine with the 2.0.18 release tag of this XBlock.

**Comment by zamanafzal** [comment]
@lgp171188 I have updated the description. Yeah with this change captions will not work on IE. But we need the video to play at all IE versions which will be accomplished with this new fix.

**Comment by lgp171188** [comment]
@zamanafzal, I tested the latest release tag of this repository - 2.0.18 without this fix on IE 11 and the video + captions worked fine. But with this fix, the captions did not work. Is this expected, particularly the part where without the fix it works okay on IE11? If there are versions other than IE 11 to test this on, can you list those versions?

**Comment by zamanafzal** [comment]
@lgp171188 IE11 v11.0.9600.19180 on windows7 videos didn't load with 2.0.18 repo. But videos will work with this fix

**Comment by xitij2000** [comment]
@zamanafzal I reviewed the previous PR that fixed caption on IE, and the video was definitely working on IE11. Are you certain there is an issue?

**Comment by zamanafzal** [comment]
@xitij2000 Yeah this issue is specific to the IE11 v11.0.9600.19180 on windows enterprise with Adobe Flash 31.

**Pull request closed without merging**
