### PR TITLE
version bump to 2.0.18

### PR DESCRIPTION
**Pull request by umarmughal824**
version bump to [aad3c97](https://github.com/edx-solutions/xblock-ooyala/commit/aad3c977f89f641fa78e9547355a879cfa8d5747) commit,

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @umarmughal824! I've created [OSPR-2805](https://openedx.atlassian.net/browse/OSPR-2805) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by umarmughal824** [comment]
@xitij2000 will you please review it?

**Comment by xitij2000** [comment]
@umarmughal824 Please bump this version to master instead? Also, why skip 17?

**Comment by xitij2000** [comment]
@umarmughal824 I'm sorry I think I was very unclear in my comment. My main point is, a version bump is already a commit, so I don't think it makes sense to version bump *to* a commit, the commit is merging to master, and is being tagged in master, so it will include all the changes, not just the commit you specified.

**Pull request merged**
