### PR TITLE
Changed default video for Ooyala player.

### PR DESCRIPTION
**Pull request by jbzdak**
Testing instructions: 

1. Add ``xblock-ooyala`` to your devstack 
2. Create a course, and add ``xblock-ooyala`` there, observe that default video is long and has bad audio. 
3. Checkout this branch. 
4. Add new ooyala player there, observe that you have a short video ending with: video upcoming.

### CODE REVIEW

**Comment by jbzdak** [comment]
@bradenmacdonald  This is now ready for review.

**Comment by bradenmacdonald** [comment]
👍

**Comment by jbzdak** [comment]
@e-kolpakov Could you please review this change as soon as possible, it's three line of code we need to merge.

**Comment by e-kolpakov** [comment]
@jbzdak not sure why do you need my approval (as braden already approved it), but :+1:

**Comment by jbzdak** [comment]
@e-kolpakov This is solutions repository and I need two reviewers :)

**Pull request merged**
