### PR TITLE
add french, german and japanese and udpate remaining languages

### PR DESCRIPTION
**Pull request by umarmughal824**
add french, german and japanese and udpate remaining languages

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @umarmughal824! I've created [OSPR-2739](https://openedx.atlassian.net/browse/OSPR-2739) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by xitij2000** [comment]
@umarmughal824 I am only seeing Show Transcript, Save and Cancel translated. The rest don't seem to work. Additionally, as commented by @viadanna on xblock-poll#45 please use the language codes used by the rest of the platform, for instance ja_JP and de_DE.

**Comment by umarmughal824** [comment]
@xitij2000 I have only received translations for these 3 to 4 works so obviously you will be able to see these only.

**Comment by xitij2000** [comment]
@umarmughal824 What I mean to say is that "Hide Transcript", "Download Transcript" and "Print Transcript" don't seem to appear translated.

**Comment by umarmughal824** [comment]
@xitij2000 Can you please share screenshot for it?

**Comment by xitij2000** [comment]
@umarmughal824 Could you create version bump PR against the development branch of edx-solution/edx-platform so this can be tested on QA? Ping me on that PR and I will approve it.

**Comment by umarmughal824** [comment]
@xitij2000 sure.

**Comment by xitij2000** [comment]
@umarmughal824 I've created the PR: https://github.com/edx-solutions/edx-platform/pull/1253

**Comment by xitij2000** [comment]
@umarmughal824 While I wasn't able to test this on QA, I did manage to stub out enough of the block's code to get translations to load, and hide translations etc are not working.

**Comment by umarmughal824** [comment]
@xitij2000 If I see its .po files, the translated strings are there for these (Hide / Print translations). Are these words translating for previous / present languages?

**Comment by xitij2000** [comment]
@umarmughal824 I just tested with the test eo language and it doesn't seem translated either. So perhaps there is another issue with the block.

**Comment by umarmughal824** [comment]
@xitij2000 I am not sure what is the issue? In my opinion its not internationalization issue becasue its not working present languages as well.

**Comment by xitij2000** [comment]
@umarmughal824 I agree. I can see the strings in the translation files. I think it perhaps you could file a bug for this? Might be an issue that needs to be fixed elsewhere.

**Comment by xitij2000** [comment]
@umarmughal824 Since there is a separate issue to look into the translation not showing up, I'm merging this.

**Comment by umarmughal824** [comment]
@xitij2000 What about version bumb? I guess it should be reverse back to edx-solutions repo.

**Comment by xitij2000** [comment]
@umarmughal824 For now, you can create a version bump PR to this commit: https://github.com/edx-solutions/xblock-ooyala/commit/aad3c977f89f641fa78e9547355a879cfa8d5747
Once it has been tested and approved we can bump up the version here and create a release.

**Pull request merged**
