### PR TITLE
Remove bit_wrapper and discovery_api as this was causing issue on IE

### PR DESCRIPTION
**Pull request by zamanafzal**
There is an issue with the latest update of 2.0.18 on some IE specific version where the video is not working. So, the workaround for that is to remove the specific files causing issues on the IE.
I have removed the bit_wrapper and discovery_api file for now as it was causing an issue on some IE versions. So, by this change Captions will not work on any IE but the video will. The work on it will be done in MCKIN-8790.

### CODE REVIEW

**Comment by zamanafzal** [comment]
@xitij2000 I have created a new PR with the same content of the previous PR
https://github.com/edx-solutions/xblock-ooyala/pull/90
as that was from the forked version and commit will be pushed through my fork. So, I have created a new PR with the edx-solution xblock repo.

**Comment by xitij2000** [comment]
@zamanafzal I'm not sure I understand how this changes anything if it's the axact same commit?

**Comment by zamanafzal** [comment]
@xitij2000 Previous PR was from github.com/zamanafzal/xblock-ooyala.git and commit will be attached with github.com/zamanafzal/xblock-ooyala.git@5755bfd265e187d065a3254ade8bc071b371a87b, so I created a new pr from 
https://github.com/edx-solutions/xblock-ooyala.git so now in edx we can install it from edx-solutions remote except zamanafzal.

**Comment by xitij2000** [comment]
@zamanafzal Sure, but that doesn't need a separate PR, you can just use the commit id already since the idea is to not merge it in that case.

**Comment by zamanafzal** [comment]
@xitij2000 Yeah but in that case commit should be with my remote name and I want to keep it with edx-solutions remote as it was.

**Comment by xitij2000** [comment]
@zamanafzal  My point is:
1. You can already use git+https://github.com/edx-solutions/xblock-ooyala.git@892c5106dd0e036a67ce6e39c24bbaca9b4fb3ad even without this PR.
2. Since this PR is essentially reverting the previous commit, why not just install an older commit instead of adding another commit and undoes an old commit: git+https://github.com/edx-solutions/xblock-ooyala.git@aad3c977f89f641fa78e9547355a879cfa8d5747
3. Even if you have to switch to a branch in the same repo, it would be better to just push the old commit to the new branch so it can be auto-approved instead of needing to be tested again since it's not easy to set up the whole Windows 7 + IE11 environment again.

**Pull request closed without merging**
