### PR TITLE
[MCKIN-6858] Changed non-China friendly CDNs to China-friendly CDNs.

### PR DESCRIPTION
**Pull request by macornwell**
This Pull Request ensures that the ooyala player can be used in China by changing out Google CDN urls for China-Friendly CDN urls.

**JIRA tickets**: MCKIN-6858

**Merge deadline**: "None" 

**Testing instructions**:
1. ...
2. Open up Developer tools in the browser and confirm that the Dosis TypeFace is coming from "http://cdn.jsdelivr.net/npm/typeface-dosis" 

**Reviewers**
- [x] @jcdyer

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @macornwell! I've created [OSPR-2184](https://openedx.atlassian.net/browse/OSPR-2184) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx-solutions/xblock-ooyala/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by jcdyer** [comment]
This looks good.  The newly linked resources have a slightly different content than the originals, but they seem to define the same fonts, and link successfully.  :+1:

**Comment by jcdyer** [comment]
When viewing ooyala blocks through apros, using this branch, I don't see the new URLs, but I don't see the old google URLs either.  I'm not sure what needs to be done to trigger this...

**Comment by jcdyer** [comment]
@macornwell Have you been able to figure out how to get the resources to load in a browser?

**Comment by macornwell** [comment]
@jcdyer  no. At no point have I ever seen google resources being loaded. I am not 100% sure these files are even in use. They were changed because they ended up in grep searches.

**Pull request merged**
